-- CÚBICA 3D — Analítica pública mínima y privada para el administrador
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- Los visitantes SOLO pueden registrar eventos mediante RPC.
-- Solo el administrador puede leer el historial de analítica.

begin;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('page_view','product_view','add_to_cart','checkout_started','purchase')),
  product_id text null,
  session_id text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name, created_at desc);

create index if not exists analytics_events_product_id_idx
  on public.analytics_events (product_id, created_at desc);

alter table public.analytics_events enable row level security;

drop policy if exists "cubica_analytics_admin_read" on public.analytics_events;
create policy "cubica_analytics_admin_read"
on public.analytics_events
for select
to authenticated
using (private.is_admin());

revoke insert, update, delete on public.analytics_events from anon, authenticated;

create or replace function public.track_public_event(
  p_event_name text,
  p_product_id text default null,
  p_session_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_event_name not in ('page_view','product_view','add_to_cart','checkout_started','purchase') then
    raise exception 'Evento no permitido';
  end if;

  if length(coalesce(p_session_id,'')) > 120 then
    raise exception 'session_id inválido';
  end if;

  insert into public.analytics_events(event_name,product_id,session_id,metadata)
  values (
    p_event_name,
    nullif(left(coalesce(p_product_id,''),120),''),
    nullif(left(coalesce(p_session_id,''),120),''),
    coalesce(p_metadata,'{}'::jsonb)
  );
end;
$$;

revoke all on function public.track_public_event(text,text,text,jsonb) from public;
grant execute on function public.track_public_event(text,text,text,jsonb) to anon, authenticated;

commit;
